# -*- coding: utf-8 -*-
"""flower_classification_vgg16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mqzrgMK9OEr7H0SKip2oyIulv3IcBJY5
"""

# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Import necessary libraries
import tensorflow as tf
from tensorflow.keras import models,applications,layers,losses,callbacks
from sklearn.metrics import confusion_matrix,classification_report
import numpy as np
import seaborn as sn
import pathlib
import PIL
import cv2
from sklearn.model_selection import train_test_split
from matplotlib import pyplot as plt

# Download and extract TensorFlow flower dataset
dataset_url = "https://storage.googleapis.com/download.tensorflow.org/example_images/flower_photos.tgz"
data_dir = tf.keras.utils.get_file('flowers', origin=dataset_url,
                                   cache_subdir='/path', untar=True)

# Convert directory path to Path object
data_dir=pathlib.Path(data_dir)
print('path:',data_dir)

# Check number of images
count=len(list(data_dir.glob('**/*.jpg')))
print('The number of images:',count)

# Show an image
roses=list(data_dir.glob('**/roses/*'))
PIL.Image.open(str(roses[0]))

# Organize image file paths and map them to integer class labels
flwers_img_dict = {
    'daisy': list(data_dir.glob('*/daisy/*')),
    'dandelion': list(data_dir.glob('*/dandelion/*')),
    'roses': list(data_dir.glob('*/roses/*')),
    'sunflowers': list(data_dir.glob('*/sunflowers/*')),
    'tulips': list(data_dir.glob('*/tulips/*'))
}
flwers_lbl_dict = {
    'daisy': 0,
    'dandelion': 1,
    'roses': 2,
    'sunflowers': 3,
    'tulips': 4
}

# Reading an image as numpy array
img=cv2.imread(str(flwers_img_dict['roses'][0]))
print('numpy array of an image:\n',img)

# check number of images in each type of flowers
for fldr_name,images in flwers_img_dict.items():
  print(fldr_name)
  print(len(images))

# Creat X,Y and resize
X,Y=[],[]
for flwr_name,images in flwers_img_dict.items():
  for image in images:
    img=cv2.imread(str(image))
    resized_img=cv2.resize(img,(100,100))
    X.append(resized_img)
    Y.append(flwers_lbl_dict[flwr_name])

# Converting X,Y to array
X=np.array(X)
Y=np.array(Y)
print('X:\n',X)
print('Y\n',Y)

# Split the data
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,random_state=0)
print('size of X_train:',X_train.shape) # check size of X_train
print('size of X_test:',X_test.shape) # check size of X_test
print('size of Y_train:',Y_train.shape) # check size of Y_train
print('size of Y_test:',Y_test.shape) # check size of Y_test

# Normalize the pixel values to the range [0, 1]
X_train=X_train/255
X_test=X_test/255

# Data augmentation to enhance model robustness
data_aug=tf.keras.Sequential([
    layers.RandomZoom(0.3),
    layers.RandomFlip("horizontal_and_vertical"),
    layers.RandomRotation(0.2),
])

# Define input shape for the MobileNetV2 model
input_shape = (100,100)
IMG_SIZE = input_shape + (3,)

# Function to create and compile the model
def my_model():
  # Load VGG16 as a feature extractor without the top classification layer
  network=applications.VGG16(input_shape=IMG_SIZE,
                             include_top=False,
                             weights='imagenet')
  network.trainable=False   # Freeze weights to prevent retraining
  model=models.Sequential([
      data_aug,
      network,
      layers.Flatten(),
      layers.Dense(128,activation='relu'),
      layers.Dense(64,activation='relu'),
      layers.Dense(32,activation='relu'),
      layers.Dense(5,activation='softmax')
  ])
  model.compile(
      optimizer='adam',
      loss=losses.sparse_categorical_crossentropy,
      metrics=['accuracy']
  )
  return model


# Function to evaluate the model
def eval(model, X, Y):
    model.evaluate(X, Y)

# Function for making predictions
def prediction(model, X, Y):
    Y_predict = model.predict(X)
    Y_pred = [np.argmax(i) for i in Y_predict]
    print('Predicted the first five labels:', Y_pred[:5])
    print('True labels of the first five elements:', Y[:5])
    return Y_pred

# Function to display classification report and confusion matrix
def report(truth, predictions):
    print(classification_report(truth, predictions))
    cm = tf.math.confusion_matrix(labels=truth, predictions=predictions)
    plt.figure(figsize=(10, 7))
    sn.heatmap(cm, annot=True, fmt='d')
    plt.xlabel('Predicted')
    plt.ylabel('Truth')

# Function to plot training and validation loss
def plot_loss(history):
    plt.figure(figsize=(10, 6))
    plt.plot(history.history['loss'], label='Train Loss')
    plt.plot(history.history['val_loss'], label='Validation Loss')
    plt.title('Training and Validation Loss')
    plt.xlabel('Epochs')
    plt.ylabel('Loss')
    plt.legend()
    plt.grid()
    plt.show()

# Function to plot training and validation accuracy
def plot_accuracy(history):
    plt.figure(figsize=(10, 6))
    plt.plot(history.history['accuracy'], label='Train Accuracy')
    plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
    plt.title('Training and Validation Accuracy')
    plt.xlabel('Epochs')
    plt.ylabel('Accuracy')
    plt.legend()
    plt.grid()
    plt.show()

# Create and train the model
model=my_model() # Instantiate the model
tb_callback=callbacks.TensorBoard(log_dir='/content/drive/logs',histogram_freq=1) # Set up TensorBoard callback
history=model.fit(X_train,Y_train,epochs= 20,validation_split=0.2,callbacks=tb_callback) # Train the model

# Plot training and validation loss and accuracy
plot_loss(history)
plot_accuracy(history)

# Evaluate the model on the test set
eval(model,X_test,Y_test)

# Make predictions
preds=prediction(model,X_test,Y_test)

#Generate a report
report(Y_test,preds)